name: Create Issues from Markdown

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (just show what would be created)'
        required: false
        default: 'false'
        type: boolean

jobs:
  create-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install @octokit/rest
      
      - name: Create issues from markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          node .github/scripts/create-issues-from-md.js
